obj-$(CONFIG_MACH_MSM8974_G3_LGU) += board-8974-g3-kr.o board-8974-g3-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_LGU_EVB) += board-8974-g3-kr.o board-8974-g3-kr-evb-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_SKT) += board-8974-g3-kr.o board-8974-g3-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_KT) += board-8974-g3-kr.o board-8974-g3-kr-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_VZW) += board-8974-g3-us.o board-8974-g3-vzw-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_LRA) += board-8974-g3-us.o board-8974-g3-lra-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_ATT) += board-8974-g3-us.o board-8974-g3-att-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_TMO_US) += board-8974-g3-us.o board-8974-g3-tmo_us-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_SPR_US) += board-8974-g3-us.o board-8974-g3-spr_us-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_USC_US) += board-8974-g3-us.o board-8974-g3-usc_us-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CMCC_CN) += board-8974-g3-cn.o board-8974-g3-cn-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CTC_CN) += board-8974-g3-cn.o board-8974-g3-cn-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CUCC_CN) += board-8974-g3-cn.o board-8974-g3-cn-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_KDDI) += board-8974-g3-kddi.o board-8974-g3-kddi-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_KDDI_EVB) += board-8974-g3-kddi.o board-8974-g3-kddi-evb-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_GLOBAL_COM) += board-8974-g3-global.o board-8974-g3-global_com-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_G3_CA) += board-8974-g3-ca.o board-8974-g3-ca-gpiomux.o
obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_MACH_LGE) += lge_charging_scenario.o
obj-$(CONFIG_LCD_KCAL) += lge_kcal_ctrl.o
obj-$(CONFIG_WIFI_CONTROL_FUNC) += wifi_bcm_lge.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-g3-rfkill.o

obj-$(CONFIG_LGE_BOOTLOADER_LOG) += lge_bootloader_log.o
obj-$(CONFIG_LGE_BOOTLOADER_TIME_CHECKER) += lge_bootloader_time_checker.o

obj-$(CONFIG_LGE_QFPROM_INTERFACE) += lge_qfprom_access.o
obj-$(CONFIG_LGE_QSDL_SUPPORT) += lge_qsdl.o

CFLAGS_devices_lge.o += -Idrivers/staging/android
