#
# Makefile for the broadcast(ISDB-T) RF/BB core.
#
#obj-$(CONFIG_LGE_BROADCAST_ONESEG)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3535)		+= broadcast_dmb_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_ONESEG_TCC3535)		+= tcc3535/
